"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-04 08:16:00.327085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caregivers_email'), 'caregivers', ['email'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('relation_to_caregiver', sa.String(length=64), nullable=True),
    sa.Column('primary_caregiver_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('phone_label', sa.String(length=64), nullable=False),
    sa.Column('ai_monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_hba1c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('last_hba1c_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_caregiver_id'], ['caregivers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_at'), 'appointments', ['scheduled_at'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dose_text', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('refill_due_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_table('medication_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_schedules_medication_id'), 'medication_schedules', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_schedules_patient_id'), 'medication_schedules', ['patient_id'], unique=False)
    op.create_table('doses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('medication_schedule_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medication_schedule_id'], ['medication_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medication_schedule_id', 'scheduled_for', name='uq_dose_schedule_time')
    )
    op.create_index(op.f('ix_doses_medication_id'), 'doses', ['medication_id'], unique=False)
    op.create_index(op.f('ix_doses_medication_schedule_id'), 'doses', ['medication_schedule_id'], unique=False)
    op.create_index(op.f('ix_doses_patient_id'), 'doses', ['patient_id'], unique=False)
    op.create_index(op.f('ix_doses_scheduled_for'), 'doses', ['scheduled_for'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('caregiver_id', sa.UUID(), nullable=True),
    sa.Column('dose_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('call_type', sa.String(length=16), nullable=False),
    sa.Column('call_reason', sa.String(length=32), nullable=True),
    sa.Column('pre_call_note', sa.Text(), nullable=True),
    sa.Column('call_control_id', sa.String(length=128), nullable=True),
    sa.Column('patient_call_control_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dose_id'], ['doses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_call_control_id'), 'calls', ['call_control_id'], unique=True)
    op.create_index(op.f('ix_calls_caregiver_id'), 'calls', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_calls_dose_id'), 'calls', ['dose_id'], unique=False)
    op.create_index(op.f('ix_calls_patient_call_control_id'), 'calls', ['patient_call_control_id'], unique=True)
    op.create_index(op.f('ix_calls_patient_id'), 'calls', ['patient_id'], unique=False)
    op.create_table('call_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('leg', sa.String(length=16), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_events_call_id'), 'call_events', ['call_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_occurred_at'), 'timeline_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_timeline_events_patient_id'), 'timeline_events', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_patient_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_occurred_at'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_call_events_call_id'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_calls_patient_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_patient_call_control_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_dose_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_caregiver_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_call_control_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_doses_scheduled_for'), table_name='doses')
    op.drop_index(op.f('ix_doses_patient_id'), table_name='doses')
    op.drop_index(op.f('ix_doses_medication_schedule_id'), table_name='doses')
    op.drop_index(op.f('ix_doses_medication_id'), table_name='doses')
    op.drop_table('doses')
    op.drop_index(op.f('ix_medication_schedules_patient_id'), table_name='medication_schedules')
    op.drop_index(op.f('ix_medication_schedules_medication_id'), table_name='medication_schedules')
    op.drop_table('medication_schedules')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_appointments_scheduled_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('patients')
    op.drop_index(op.f('ix_caregivers_email'), table_name='caregivers')
    op.drop_table('caregivers')
    # ### end Alembic commands ###
